//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4charm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4charm.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4chan.
        /// </summary>
        public static string AboutPage_4chan {
            get {
                return ResourceManager.GetString("AboutPage_4chan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4chan API.
        /// </summary>
        public static string AboutPage_4chanAPI {
            get {
                return ResourceManager.GetString("AboutPage_4chanAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is sourced from.
        /// </summary>
        public static string AboutPage_ContentSourcedFrom {
            get {
                return ResourceManager.GetString("AboutPage_ContentSourcedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string AboutPage_Credits {
            get {
                return ResourceManager.GetString("AboutPage_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All title and intellectual property rights in and to the content which may be accessed through use of the 4charm is the property of the respective content owner and may be protected by applicable copyright or other intellectual property laws and treaties. Use of this application grants you no rights to use such content..
        /// </summary>
        public static string AboutPage_Disclaimer {
            get {
                return ResourceManager.GetString("AboutPage_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HtmlAgilityPack.
        /// </summary>
        public static string AboutPage_HtmlAgilityPack {
            get {
                return ResourceManager.GetString("AboutPage_HtmlAgilityPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string AboutPage_Publisher {
            get {
                return ResourceManager.GetString("AboutPage_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight MediaViewer.
        /// </summary>
        public static string AboutPage_SilverlightMediaViewer {
            get {
                return ResourceManager.GetString("AboutPage_SilverlightMediaViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight Toolkit.
        /// </summary>
        public static string AboutPage_SilverlightToolkit {
            get {
                return ResourceManager.GetString("AboutPage_SilverlightToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolStack C# PNG Writer.
        /// </summary>
        public static string AboutPage_ToolstackPNG {
            get {
                return ResourceManager.GetString("AboutPage_ToolstackPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddBoardPage_Add {
            get {
                return ResourceManager.GetString("AddBoardPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string AddBoardPage_Description {
            get {
                return ResourceManager.GetString("AddBoardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string AddBoardPage_Name {
            get {
                return ResourceManager.GetString("AddBoardPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NSFW).
        /// </summary>
        public static string AddBoardPage_NSFW {
            get {
                return ResourceManager.GetString("AddBoardPage_NSFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add board.
        /// </summary>
        public static string AddBoardPage_Title {
            get {
                return ResourceManager.GetString("AddBoardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ApplicationBar_Clear {
            get {
                return ResourceManager.GetString("ApplicationBar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string ApplicationBar_Edit {
            get {
                return ResourceManager.GetString("ApplicationBar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock orientation.
        /// </summary>
        public static string ApplicationBar_LockOrientation {
            get {
                return ResourceManager.GetString("ApplicationBar_LockOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new thread.
        /// </summary>
        public static string ApplicationBar_NewThread {
            get {
                return ResourceManager.GetString("ApplicationBar_NewThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string ApplicationBar_Refresh {
            get {
                return ResourceManager.GetString("ApplicationBar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string ApplicationBar_Reply {
            get {
                return ResourceManager.GetString("ApplicationBar_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ApplicationBar_Save {
            get {
                return ResourceManager.GetString("ApplicationBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scroll to bottom.
        /// </summary>
        public static string ApplicationBar_ScrollToBottom {
            get {
                return ResourceManager.GetString("ApplicationBar_ScrollToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scroll to top.
        /// </summary>
        public static string ApplicationBar_ScrollToTop {
            get {
                return ResourceManager.GetString("ApplicationBar_ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string ApplicationBar_Search {
            get {
                return ResourceManager.GetString("ApplicationBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string ApplicationBar_Send {
            get {
                return ResourceManager.GetString("ApplicationBar_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string ApplicationBar_Submit {
            get {
                return ResourceManager.GetString("ApplicationBar_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlock orientation.
        /// </summary>
        public static string ApplicationBar_UnlockOrientation {
            get {
                return ResourceManager.GetString("ApplicationBar_UnlockOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unwatch.
        /// </summary>
        public static string ApplicationBar_Unwatch {
            get {
                return ResourceManager.GetString("ApplicationBar_Unwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watch.
        /// </summary>
        public static string ApplicationBar_Watch {
            get {
                return ResourceManager.GetString("ApplicationBar_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4charm.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string BoardsPage_About {
            get {
                return ResourceManager.GetString("BoardsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add board.
        /// </summary>
        public static string BoardsPage_AddBoard {
            get {
                return ResourceManager.GetString("BoardsPage_AddBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string BoardsPage_All {
            get {
                return ResourceManager.GetString("BoardsPage_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the + button to add some boards..
        /// </summary>
        public static string BoardsPage_AllEmpty {
            get {
                return ResourceManager.GetString("BoardsPage_AllEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board is already pinned..
        /// </summary>
        public static string BoardsPage_AlreadyPinned {
            get {
                return ResourceManager.GetString("BoardsPage_AlreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string BoardsPage_Favorites {
            get {
                return ResourceManager.GetString("BoardsPage_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap and hold boards on the all boards list to add favorites!.
        /// </summary>
        public static string BoardsPage_FavoritesEmpty {
            get {
                return ResourceManager.GetString("BoardsPage_FavoritesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string BoardsPage_Feedback {
            get {
                return ResourceManager.GetString("BoardsPage_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string BoardsPage_History {
            get {
                return ResourceManager.GetString("BoardsPage_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history at the moment..
        /// </summary>
        public static string BoardsPage_HistoryEmpty {
            get {
                return ResourceManager.GetString("BoardsPage_HistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string BoardsPage_More {
            get {
                return ResourceManager.GetString("BoardsPage_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        public static string BoardsPage_Rate {
            get {
                return ResourceManager.GetString("BoardsPage_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string BoardsPage_Settings {
            get {
                return ResourceManager.GetString("BoardsPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchlist.
        /// </summary>
        public static string BoardsPage_Watchlist {
            get {
                return ResourceManager.GetString("BoardsPage_Watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchlist is empty. Add some threads!.
        /// </summary>
        public static string BoardsPage_WatchlistEmpty {
            get {
                return ResourceManager.GetString("BoardsPage_WatchlistEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string BoardTemplate_AddToFavorites {
            get {
                return ResourceManager.GetString("BoardTemplate_AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string BoardTemplate_PinToStart {
            get {
                return ResourceManager.GetString("BoardTemplate_PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove from favorites.
        /// </summary>
        public static string BoardTemplate_RemoveFromFavorites {
            get {
                return ResourceManager.GetString("BoardTemplate_RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image download failed..
        /// </summary>
        public static string ImageViewerPage_ImageFailed {
            get {
                return ResourceManager.GetString("ImageViewerPage_ImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string ImageViewerPage_ImageSaved {
            get {
                return ResourceManager.GetString("ImageViewerPage_ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to Saved Pictures....
        /// </summary>
        public static string ImageViewerPage_SavingImage {
            get {
                return ResourceManager.GetString("ImageViewerPage_SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha data is corrupt..
        /// </summary>
        public static string NewThreadPage_CaptchaCorrupt {
            get {
                return ResourceManager.GetString("NewThreadPage_CaptchaCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose file.
        /// </summary>
        public static string NewThreadPage_ChooseFile {
            get {
                return ResourceManager.GetString("NewThreadPage_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPLY TO - /{0}/ - {1}.
        /// </summary>
        public static string NewThreadPage_NewPostPageTitle {
            get {
                return ResourceManager.GetString("NewThreadPage_NewPostPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW THREAD - /{0}/.
        /// </summary>
        public static string NewThreadPage_NewThreadPageTitle {
            get {
                return ResourceManager.GetString("NewThreadPage_NewThreadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error encountered submitting thread..
        /// </summary>
        public static string NewThreadPage_UnknownError {
            get {
                return ResourceManager.GetString("NewThreadPage_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PostsPage_Comment {
            get {
                return ResourceManager.GetString("PostsPage_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the posts :(.
        /// </summary>
        public static string PostsPage_Error {
            get {
                return ResourceManager.GetString("PostsPage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string PostsPage_PostSuccess {
            get {
                return ResourceManager.GetString("PostsPage_PostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting....
        /// </summary>
        public static string PostsPage_Submitting {
            get {
                return ResourceManager.GetString("PostsPage_Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string PostsPage_Verification {
            get {
                return ResourceManager.GetString("PostsPage_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy text.
        /// </summary>
        public static string PostTemplate_CopyText {
            get {
                return ResourceManager.GetString("PostTemplate_CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show quotes.
        /// </summary>
        public static string PostTemplate_SeeQuotes {
            get {
                return ResourceManager.GetString("PostTemplate_SeeQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable manual refresh.
        /// </summary>
        public static string SettingsPage_ManualRefresh {
            get {
                return ResourceManager.GetString("SettingsPage_ManualRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landscape.
        /// </summary>
        public static string SettingsPage_OrientationLandscape {
            get {
                return ResourceManager.GetString("SettingsPage_OrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation lock.
        /// </summary>
        public static string SettingsPage_OrientationLock {
            get {
                return ResourceManager.GetString("SettingsPage_OrientationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portrait.
        /// </summary>
        public static string SettingsPage_OrientationPortrait {
            get {
                return ResourceManager.GetString("SettingsPage_OrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocked.
        /// </summary>
        public static string SettingsPage_OrientationUnlocked {
            get {
                return ResourceManager.GetString("SettingsPage_OrientationUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show stickies.
        /// </summary>
        public static string SettingsPage_ShowStickies {
            get {
                return ResourceManager.GetString("SettingsPage_ShowStickies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tripcodes.
        /// </summary>
        public static string SettingsPage_ShowTripcodes {
            get {
                return ResourceManager.GetString("SettingsPage_ShowTripcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize gallery and post views.
        /// </summary>
        public static string SettingsPage_SynchronizeViews {
            get {
                return ResourceManager.GetString("SettingsPage_SynchronizeViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use HTTPS.
        /// </summary>
        public static string SettingsPage_UseHTTPS {
            get {
                return ResourceManager.GetString("SettingsPage_UseHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the text size in the thread, catalog, and post views..
        /// </summary>
        public static string TextSizeSlider_Description {
            get {
                return ResourceManager.GetString("TextSizeSlider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string TextSizeSlider_SampleText {
            get {
                return ResourceManager.GetString("TextSizeSlider_SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text size.
        /// </summary>
        public static string TextSizeSlider_TextSize {
            get {
                return ResourceManager.GetString("TextSizeSlider_TextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catalog.
        /// </summary>
        public static string ThreadsPage_Catalog {
            get {
                return ResourceManager.GetString("ThreadsPage_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the threads :(.
        /// </summary>
        public static string ThreadsPage_Error {
            get {
                return ResourceManager.GetString("ThreadsPage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threads.
        /// </summary>
        public static string ThreadsPage_Threads {
            get {
                return ResourceManager.GetString("ThreadsPage_Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watchlist.
        /// </summary>
        public static string ThreadsPage_Watchlist {
            get {
                return ResourceManager.GetString("ThreadsPage_Watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose tile.
        /// </summary>
        public static string TilePicker_ChooseTile {
            get {
                return ResourceManager.GetString("TilePicker_ChooseTile", resourceCulture);
            }
        }
    }
}
